packages:
  - spectra6
  - web

allowBuilds:
  esbuild: true

catalog:
  "@types/node": 26.1.1
  "@eslint/js": 10.0.1
  eslint: 10.7.0
  eslint-config-prettier: 10.1.8
  typescript-eslint: 8.65.0
  typescript: 7.0.2

catalogs:
  typescript:
    typescript: 'npm:@typescript/typescript6@6.0.2'
    '@typescript/native': 'npm:typescript@7.0.2'

saveExact: true